-- 070_ai_memory_card.sql
-- Adds columns to store AI-generated customer memory cards.
--
-- The memory card is a structured JSON summary generated by the LLM that
-- includes: communication preferences, buying behavior, interests, sentiment,
-- churn risk, next best action, and key facts.
--
-- Cached for 24 hours to avoid re-running the LLM on every view.

ALTER TABLE customers ADD COLUMN IF NOT EXISTS ai_memory_card JSONB;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS ai_memory_card_at TIMESTAMPTZ;

COMMENT ON COLUMN customers.ai_memory_card IS 'AI-generated structured memory card (JSON). Cached for 24h. See /api/ai/memory-card.';
COMMENT ON COLUMN customers.ai_memory_card_at IS 'When the ai_memory_card was last generated. Used for cache TTL.';
